### PR TITLE
Add  stacktrace to the log

### PR DESCRIPTION
**Pull request by Sathiyakugan**
Fixes the comment on https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/118/files#r517247217

### CODE REVIEW

**Comment by darshanasbg** [comment]
Don't we need to throw the the exception?

**Comment by Sathiyakugan** [comment]
> Don't we need to throw the the exception?

There we shouldn't break the flow because the exception occurs. 
We didn't break the flow and let the flow as it is even before adding the audit logs when there was no SP for Consumer key, Which means we have some exceptional flows. 
When we use the SP from MDC the one who uses should check for the null.

**Comment by JKAUSHALYA** [comment]
> > Don't we need to throw the the exception?
> 
> Think of a scenario where there is no SP for the Consumer key.
> 
> What will be the possible scenario which causes this?
>       only when an error occurs or an exceptional flow occurs.
>             if an error occurred :
>                   there should be an error thrown.
> 
> If we get to this point https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/118/files#r517247217
> 
> This means we are executing an exceptional flow. or an error has been thrown earlier and handled properly.
> So form here we don't need to throw the error again.
> 
> Hence the one who uses the SP name derived in this improvement should check for the null before using it.

So if there is no service provider, don't we need to break the flow? Otherwise, it will send a successful authentication result for erroneous service providers as well. Is it acceptable?

**Comment by Sathiyakugan** [comment]
> > > Don't we need to throw the the exception?
> > 
> > 
> > Think of a scenario where there is no SP for the Consumer key.
> > What will be the possible scenario which causes this?
> >       only when an error occurs or an exceptional flow occurs.
> >             if an error occurred :
> >                   there should be an error thrown.
> > If we get to this point https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/118/files#r517247217
> > This means we are executing an exceptional flow. or an error has been thrown earlier and handled properly.
> > So form here we don't need to throw the error again.

We don't need to since the place where we get the SP won't cause any error. Since the method that we called to get the SP throws the exception It's mandatory to handle it. That's the reason why there's a try-catch block

**Review by somindatommy — APPROVED** [review]

**Pull request merged**
